TH-11: Themes > Can’t modify/hide "add comment button" in product review
youcan-shop/youcan-themes pull request #18
Opened 2024-08-07 08:24 UTC by MohamedJamoun

## JIRA Ticket

Ticket: [TH-11](https://youcanshop.atlassian.net/browse/TH-11).

## Prerequisites

* [ ] Check this branch locally and run `pnpm run release`
* [ ] 3 new files will be generated in this format `theme name + date + .zip`
* [ ] Upload generated file locally or in seller-area test env

## QA Steps

* [ ] Go to /something
* [ ] Verify said thing

## Note

Leave empty when you have nothing to say.

2024-08-07 11:16 UTC, ibrilBadreddine requested changes
The PR looks good. I left u some suggestions (applied to all themes). Also, please avoid making changes to `.css` files and keep `.scss` files only.

2024-08-07 11:16 UTC, ibrilBadreddine commented on themes/aura/sections/product-reviews.liquid
>  {% schema %}
```suggestion
{%- schema -%}
...
{%- endschema -%}
```

2024-08-08 09:27 UTC, MohamedJamoun commented
> The PR looks good. I left u some suggestions (applied to all themes). Also, please avoid making changes to `.css` files and keep `.scss` files only.

The SCSS is getting converted to CSS, browser only understands CSS

2024-08-08 09:28 UTC, ibrilBadreddine approved these changes

2024-08-09 08:17 UTC, merged