TH-9: Themes > Slider Image button colors can’t be changed
youcan-shop/youcan-themes pull request #7
Opened 2024-07-31 15:06 UTC by ibrilBadreddine

## JIRA Ticket

[TH-9](https://youcanshop.atlassian.net/browse/TH-9)

## QA Steps

-  [ ]  Check this branch locally and run `pnpm run release`
-  [ ]  3 new files will be generated in this format `theme name + date + .zip`
-  [ ]  Upload generated file locally or in seller-area test env

## Note

Please read the ticket description.

[TH-9]: https://youcanshop.atlassian.net/browse/TH-9?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-08-01 11:05 UTC, eihabkhan1 requested changes

2024-08-01 11:05 UTC, eihabkhan1 commented on themes/aura/snippets/slider.liquid
Since we now give the seller the ability to change the foreground and background colors, we can remove the previous "static" color styles.
Desktop: https://github.com/youcan-shop/youcan-themes/blob/fde95b7cdbf8163ffc97bea282b1a1b46f2bf576/themes/aura/styles/desktop-slider.scss#L43 and https://github.com/youcan-shop/youcan-themes/blob/fde95b7cdbf8163ffc97bea282b1a1b46f2bf576/themes/aura/styles/desktop-slider.scss#L34
Mobile: https://github.com/youcan-shop/youcan-themes/blob/fde95b7cdbf8163ffc97bea282b1a1b46f2bf576/themes/aura/styles/mobile-slider.scss#L24 and https://github.com/youcan-shop/youcan-themes/blob/fde95b7cdbf8163ffc97bea282b1a1b46f2bf576/themes/aura/styles/mobile-slider.scss#L15

After removing those styles, we won't need the `!important` in /snippets/slider.liquid

> [!Note]
> This applies to all themes

2024-08-01 14:56 UTC, BadreddineIbril commented
Request changes are done, now waiting for GitHub's mercy.

2024-08-05 11:06 UTC, eihabkhan1 commented on themes/meraki/snippets/slider.liquid
> +  margin-top: 1em;
Are we sure about this change 👀

2024-08-05 11:29 UTC, eihabkhan1 commented
To check:
- `margin-top: 1em;` in themes/meraki/snippets/slider.liquid and themes/harmony/snippets/slider.liquid
- Changes for mobile-slider were done to Aura only themes/aura/styles/mobile-slider.scss, meraki and harmony remain unchanged

2024-08-05 14:02 UTC, eihabkhan1 approved these changes

2024-08-05 14:08 UTC, merged